add permissions handling, improve "undo" script
set permissions of system files before installing, allowing use of
download from github

improve experimental "undo" script

diff --git a/undo b/undo
--- a/undo
+++ b/undo
@@ -1,9 +1,10 @@
 #!/bin/bash
 # An attempt to undo the install and revert to the original
 # base cli Debian system.
-# NB This is an experimental script, 100% success is not guaranteed. 
+# NB This is an experimental script, 100% success is not guaranteed.
 # USAGE
-# This script should come in a folder called cb-?-netinstall,
+# This script should come in a folder called cb-?-netinstall
+# (or also be found in .cb-netinstall-logs),
 # along with a collection of other necessary files.
 # Change directory (cd) into that folder and run
 # ./undo
@@ -17,14 +18,19 @@ set -o nounset # do not accept unset variables
 
 [[ -r config ]] || { echo "$0: Cannot find necessary file \"config\"" >&2; exit 1; }
 . config
-for i in log_dir backup_dir backup_suffix necessary_files replaced_dirs
+for i in log_dir backup_dir backup_suffix
 do
-    [[ $i ]] || { echo "$0: Config variable $i has not been set." >&2; exit 1; }
+    [[ $i ]] || { echo "$0: Config variable $i has not been set. Please check the \"config\" file." >&2; exit 1; }
 done
-uninstall_backup_dir="${backup_dir}"/undo
+
 install_backup_dir="${backup_dir}"/install
 snapshots_dir="${backup_dir}"/snapshots
-backup_dir="$uninstall_backup_dir"
+backup_dir="${backup_dir}"/undo
+install_log_dir=$log_dir
+log_dir="$log_dir"/undo-logs
+
+necessary_files=(pkgs-manual pkgs-norecs pkgs-auto) # array
+necessary_logfiles=("${install_log_dir}"/{sysfiles-added,sysdirs-added,userfiles-added,userdirs-added,netinstall-core-apps,netinstall-auto-apps})
 
 logfile=error.log # temporary logfile in installer directory
 user=$USER
@@ -65,9 +71,21 @@ confirm() { # $1 is message, $2 is desired return value: 0 or 1 (passed to 'give
     echo "
 $1
 (press enter to continue, any other key to exit)
-"
+" | tee -a "$logfile"
     read -srn1
     [[ $REPLY ]] && giveup "terminated by $user, goodbye!" $2
+    log "$user chose to continue"
+}
+
+option() {
+    echo "
+$1
+(press enter to agree, any other key to pass)
+" | tee -a "$logfile"
+    read -srn1
+    [[ $REPLY ]] && { log "$user did not agree"; return 1; }
+    log "$user agreed"
+    return 0
 }
 
 giveup() { # $1 is message, $2 is desired return value: 0 or 1
@@ -81,6 +99,22 @@ giveup() { # $1 is message, $2 is desired return value: 0 or 1
     exit ${2:-1}
 }
 
+net_test() {
+    tries=4
+    printf 'checking network connection... ' | tee -a "$logfile"
+    while [[ $tries -gt 0 ]]
+    do
+        wget -O - 'http://ftp.debian.org/debian/README' >/dev/null 2>&1 && {
+            msg '[OK]'
+            return 0
+        }
+        ((tries--))
+        sleep 1
+    done
+    msg '[FAILED]'
+    return 1
+}
+
 trap 'giveup "Script terminated." 1' 1 2 3 15
 [[ $user = root ]] && giveup "This script should be run by a normal user, not root" 1
 
@@ -88,7 +122,7 @@ log "
 ########################################################################
 Starting uninstall script for $user at $(date)"
 
-clear
+#clear
 tput bold
 echo "Hi $user, this is the uninstall script!"
 tput sgr0
@@ -102,24 +136,26 @@ but might be able to restore something close to a basic Debian cli system.
 "
 confirm "ARE YOU SURE you want to run the UNINSTALL script now?" 0
 
+[[ -d "$install_log_dir" ]] || giveup "Could not find necessary log directory $install_log_dir" 1
+[[ -d "$install_backup_dir" ]] || confirm "Could not find backup directory $install_backup_dir
+It may not be possible to restore some system files to the exact state
+they were in before running the install script.
+Would you like to continue the uninstall anyway?" 1
+
 # check for needed files
 missing_files=
-for i in $necessary_files
+for i in "${necessary_files[@]}" "${necessary_logfiles[@]}"
 do
     [[ -r $i ]] || missing_files+=" $i"
 done
-[[ $missing_files ]] && giveup "Some necessary files or folders were missing: $missing_files" 1 || msg "Necessary files: OK"
+[[ $missing_files ]] && giveup "Some necessary files were missing: $missing_files" 1 || msg "Necessary files: OK"
 
 # setup logfile
-[[ -d "$log_dir" ]] || giveup "Could not find necessary log directory $log_dir" 1
-install_log_dir=$log_dir
-log_dir="$log_dir/undo"
 mkdir -p "$log_dir" || giveup "failed to make $log_dir" 1
 cat "$logfile" >> "$log_dir"/uninstall.log
 rm "$logfile" # finished with temporary logfile
 logfile="$log_dir"/uninstall.log # this logfile will remain after the install
 bigmsg "messages are being saved to $logfile"
-#cp pkgs-manual pkgs-auto "$log_dir"
 
 # check debian version FIXME Is /etc/debian_version the best way?
 grep -q '\(wheezy\|\(^\|[^a-zA-Z0-9.]\)7\($\|[^a-zA-Z0-9]\)\)' /etc/debian_version && msg "Debian version: OK"|| { warnlog "/etc/debian_version reads: $(cat /etc/debian_version)"
@@ -163,6 +199,7 @@ install_sysdir() { # recursively copy contents of $1 into $2, make backups in $3
         [[ $i = *$'\n'* ]] && giveup "Line-break in filename: $i
 Please contact the software provider, or remove this file
 before running the script again." 1
+        [[ $i = *~ ]] && { msg "ignoring backup file $i"; continue; }
         filename="${i##*/}"
         target="${2%/}/${filename}" # avoid double slash if $2 is /
         if sudo test -d "$i"
@@ -254,16 +291,73 @@ before running the script again." 1
 
 ########## end file copying functions ##########
 
-
 bigmsg "Uninstalling packages."
 
-sudo apt-get --quiet purge $(cat pkgs-manual pkgs-auto pkgs-norecs | sed 's/\#.*$//') > >( tee -a "$logfile" ) 2>&1 || errmsg "'apt-get --quiet purge' returned an error.
+pkgs_to_remove=($(comm -23 <(sed 's/\#.*$//' pkgs-manual pkgs-norecs | sort) <(sort ${install_log_dir}/netinstall-core-apps)))
+sudo apt-get purge "${pkgs_to_remove[@]}" > >( tee -a "$logfile" ) 2>&1 || errmsg "'apt-get purge' returned an error.
 There may be some information in ${logfile}."
 
 bigmsg "Removing dependencies..."
-sudo apt-get --quiet autoremove > >( tee -a "$logfile" ) 2>&1 || errmsg "There was a problem with 'apt-get autoremove'.
-There may be some information in ${logfile}." 1
+sudo apt-get --quiet --purge autoremove > >( tee -a "$logfile" ) 2>&1 || errmsg "There was a problem with 'apt-get autoremove'.
+There may be some information in ${logfile}."
 bigmsg "Packages uninstalled"
+
+bigmsg "Restoring original packages"
+
+pkgs_to_remove=($(comm -23 <(apt-mark showmanual|sort) <(sort ${install_log_dir}/netinstall-core-apps)))
+pkgs_to_restore=($(comm -13 <(apt-mark showmanual|sort) <(sort ${install_log_dir}/netinstall-core-apps)))
+missing_auto=($(comm -13 <(apt-mark showauto|sort) <(sort ${install_log_dir}/netinstall-auto-apps)))
+
+[[ ${#pkgs_to_remove[@]} -gt 0 ]] && {
+    option "Some extra packages seem to have been installed since the netinstall script was run:
+${pkgs_to_remove[@]}
+Would you like to remove the above packages now?" && {
+        sudo apt-get purge "${pkgs_to_remove[@]}" > >( tee -a "$logfile" ) 2>&1 || errmsg "'apt-get purge' returned an error.
+There may be some information in ${logfile}."
+    }
+}
+
+netup=false
+[[ ${#pkgs_to_restore[@]} -gt 0 || ${#missing_auto[@]} -gt 0 ]] && {
+    while true
+    do
+        net_test && { netup=true; break;}
+        option "Your network seems to be down.
+Would you like to try to fix it (maybe edit /etc/network/interfaces)
+and check again, or skip installing missing packages?
+(Enter when ready to to check again, other key to skip.)" || { netup=false; break;}
+    done
+}
+$netup && {
+    [[ ${#pkgs_to_restore[@]} -gt 0 ]] && {
+        option "Some packages seem to have been removed since the netinstall script was run:
+    ${pkgs_to_restore[@]}
+    Would you like to install the above packages now?" && {
+            sudo apt-get install "${pkgs_to_restore[@]}" > >( tee -a "$logfile" ) 2>&1 || errmsg "'apt-get install' returned an error.
+    There may be some information in ${logfile}."
+        }
+    }
+    [[ ${#missing_auto[@]} -gt 0 ]] && {
+        option "Some auto-installed packages seem to be missing:
+    ${missing_auto[@]}
+    Would you like to install the above packages now?" && {
+            sudo apt-get install "${missing_auto[@]}" > >( tee -a "$logfile" ) 2>&1 || errmsg "'apt-get install' returned an error.
+    There may be some information in ${logfile}."
+        }
+    }
+}
+
+msg "removing unnecessary packages"
+sudo apt-get --purge autoremove > >( tee -a "$logfile" ) 2>&1 || errmsg "There was a problem with 'apt-get autoremove'.
+There may be some information in ${logfile}."
+
+msg "marking auto packages"
+sudo apt-mark auto $(< ${install_log_dir}/netinstall-auto-apps) > >( tee -a "$logfile" ) 2>&1 || errmsg "unable to mark packages as auto-installed"
+
+bigmsg "Restoring former system files."
+shopt -s dotglob # want dotfiles too
+install_sysdir "${install_backup_dir}" / "${backup_dir}"
+shopt -u dotglob
 
 bigmsg "removing unnecessary files and directories"
 mapfile -t unwanted_sysfiles < <(sed 's/\#.*$//' "$install_log_dir"/sysfiles-added)
@@ -288,21 +382,6 @@ do
         sudo rm -r "$i"  > >( tee -a "$logfile" ) 2>&1 || errmsg "failed to remove system directory $i"
     else
         msg "directory $i does not exist"
-    fi
-done
-
-bigmsg "Restoring former system files."
-mapfile -t replace_sysfiles < <(sed 's/\#.*$//' "$install_log_dir"/sysfiles-replaced)
-for i in "${replace_sysfiles[@]}"
-do
-    [[ $i ]] || continue # blank line
-    if sudo test -e "${install_backup_dir}$i"
-    then
-        msg "restoring file $i"
-        sudo test -e "$i" && are_identical "${install_backup_dir}$i" "$i" && { msg "${install_backup_dir}$i and $i are identical"; continue; }
-        sudo cp "${install_backup_dir}$i" "$i"  > >( tee -a "$logfile" ) 2>&1 || errmsg "failed to restore system file $i"
-    else
-        msg "cannot restore file $i. ${install_backup_dir}$i does not exist"
     fi
 done
 
@@ -339,10 +418,18 @@ done
         [[ $i ]] || continue # blank line
         sudo test -e "${snapshots_dir}${i}" || { errmsg "no snapshot ${snapshots_dir}${i} exists"; continue;}
         msg "restoring snapshot of $i from ${snapshots_dir}${i}"
-        sudo mkdir -p "${uninstall_backup_dir}${i%/*}" > >( tee -a "$logfile" ) 2>&1 || errmsg "Failed to make directory ${uninstall_backup_dir}${i%/*}"
-        sudo test -e "$i" && sudo mv "$i" "${uninstall_backup_dir}${i%/*}" > >( tee -a "$logfile" ) 2>&1 || errmsg "Failed to move $i to ${uninstall_backup_dir}${i%/*}."
+        sudo test -e "$i" && {
+            sudo mkdir -p "${backup_dir}${i%/*}" > >( tee -a "$logfile" ) 2>&1 || errmsg "Failed to make directory ${backup_dir}${i%/*}"
+            sudo test -e "${backup_dir}${i}" && {
+                msg "backup copy of $i already exists at ${backup_dir}${i}
+making new copy at ${backup_dir}${i}${backup_suffix}"
+                sudo mv -T "$i" "${backup_dir}${i}${backup_suffix}" > >( tee -a "$logfile" ) 2>&1 || errmsg "Failed to move $i to ${backup_dir}${i}${backup_suffix}"
+            } || {
+                sudo mv "$i" "${backup_dir}${i%/*}" > >( tee -a "$logfile" ) 2>&1 || errmsg "Failed to move $i to ${backup_dir}${i%/*}"
+            }
+        }
         sudo mkdir -p "${i%/*}" > >( tee -a "$logfile" ) 2>&1 || errmsg "Failed to make directory ${i%/*}"
-        sudo cp "${snapshots_dir}${i}" "${i%/*}"
+        sudo cp -a "${snapshots_dir}${i}" "${i%/*}" > >( tee -a "$logfile" ) 2>&1 || errmsg "Failed to copy ${snapshots_dir}${i} into ${i%/*}"
     done
 }
 
@@ -351,5 +438,7 @@ shopt -s dotglob # want dotfiles too
 install_userdir /etc/skel $HOME
 shopt -u dotglob
 
-bigmsg "UNINSTALL FINISHED!"
+bigmsg "UNINSTALL FINISHED"
+msg "You may find some system files are still different
+from their original state..."
 exit
